### ISSUE TITLE
predictInterval: crossed effects error

### ISSUE THREAD

**Issue by miked58** [jknowles/merTools#108] opened 2019-09-11 16:33 UTC
I have a model of the form y ~ (x1 + x2 | group1) + (x3 | group2) + regressors, and I'm getting the following error: 

Error in FUN(X[[i]], ...) : 
  random effects specified in re.form that were not present in original model

Traceback shows the snag is hit here:
4: lapply(seq_along(nRnms), function(i) {
       rname <- nRnms[i]
       if (!all(Rcnms[[i]] %in% names(re[[rname]]))) 
           stop("random effects specified in re.form that were not present in original model")
       re_x[[rname]][, Rcnms[[i]]]
   })
3: mkNewReTrms(object = model, newdata = newdata, re.form, na.action = "na.pass", 
       allow.new.levels = TRUE)
2: buildModelMatrix(model = merMod, newdata = newdata)
1: predictInterval(mm2, holdout)

If I remove the x3 random effect and leave the intercept for group2, I'm able to get predictions. Are crossed effects supported and this is a bug, or is the functionality not yet available?

**Comment by jknowles** [comment] 2019-09-16 21:19
This should work. Can you put together a [reprex](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219) so I can investigate this further and see what might be going on?

**Comment by jknowles** [comment] 2019-09-29 00:32
Closing this due to lack of a reprex. Feel free to reopen if you can reproduce this.

**Closed by jknowles** 2019-09-29 00:32 UTC
