### ISSUE TITLE
`predictInterval()` can't handle multiple random coefficients per group

### ISSUE THREAD

**Issue by carlbfrederick** [jknowles/merTools#8] opened 2015-07-06 20:45 UTC
Somewhere along the way, they changed the `lme4::ranef()` so that it no longer will return the conditional covariance matrix of the estimated random effects when there is more than one random term per level (e.g. an intercept and slope or no intercepts and 2 slopes).

In `predictInterval()` [line 62](https://github.com/jknowles/merTools/blob/master/R/merPredict.R#L62), `lme4::ranef` throws the following warning: "conditional variances not currently available via ranef when there are multiple terms per factor" and thus  [line 68](https://github.com/jknowles/merTools/blob/master/R/merPredict.R#L68) crashes the function.

Not sure that we can fix it until they decide to support this feature again, so for now, we may just have to note this in the documentation.

**Comment by jknowles** [comment] 2015-07-07 14:18
Which version of lme4 is this issue on? If we can narrow down and reproduce, we can look to uncover that and talk to the `lme4` authors. I thought I had a suite of tests that included checking this for multiple terms and it was passing previously.

**Comment by jknowles** [comment] 2015-07-07 15:02
Nope. Just realized I was wrong. There is no test for that. I'm adding it in and trying to create a MWE to find out how to get the `lme4` team to look into this.

**Comment by carlbfrederick** [comment] 2015-07-07 15:30
I just updated to the latest stable 1.1.8. I am not sure which version I had previously  where it was working.

**Comment by jknowles** [comment] 2015-07-07 15:33
I added a test to our test suite, take a look at the latest commit and see what you think. It passes on my machine so maybe I'm not properly recreating the problem.

**Comment by jknowles** [comment] 2015-07-07 15:46
And it issues a ton of warnings -- maybe that's where the problem is coming up, not causing a crash on my machine, but goofing the calculation nonetheless.

**Comment by carlbfrederick** [comment] 2015-07-07 16:10
Yeah. I think I only noticed it cause I was trying to make a shiny app wrapper function. It did not like the null values. I will test it on my machine later this afternoon when I get in.

**Comment by jknowles** [comment] 2015-07-07 17:42
Check the latest build and the last test I added to `test_predict.R`, which I think covers the case you are describing, but provides predictions with confidence intervals -- but also issues a ton of warnings.

**Comment by carlbfrederick** [comment] 2015-07-07 18:56
Yeah, the function doesn't crash because when we calculate the yhat and collapse the 3D array ([line 118](https://github.com/jknowles/merTools/blob/master/R/merPredict.R#L118)) I have included na.rm=TRUE, but if you step through the function, the REsimA object for group 2 ("BROOD") is full of `NaN`s

**Comment by jknowles** [comment] 2015-07-07 19:04
Makes sense. OK. I'll create a MWE and submit the issue to `lme4

**Comment by jknowles** [comment] 2015-07-07 19:08
In the meantime, we should definitely issue a warning there that is more informative and says that the confidence intervals will be incorrect.

**Comment by jknowles** [comment] 2015-07-08 12:48
Did some debugging and this gets weird:

```
data(grouseticks)
  grouseticks$HEIGHT <- scale(grouseticks$HEIGHT)
  grouseticks <- merge(grouseticks, grouseticks_agg[, 1:3], by = "BROOD")
  grouseticks$TICKS_BIN <- ifelse(grouseticks$TICKS >=1, 1, 0)
  # GLMER 2 level + slope
  form <- TICKS_BIN ~ YEAR + HEIGHT +(1 + HEIGHT|BROOD) + (1|LOCATION)
  glmer2LevSlope  <- glmer(form, family="binomial",data=grouseticks,
                           control = glmerControl(optimizer="bobyqa",
                                                  optCtrl=list(maxfun = 1e5)))
```
If I look at the attributes of the random-effects for `BROOD`, I do get a valid series of variance-covariance matrices: 

```
> attr(myRE[["BROOD"]], which = "postVar")[, , 1]
          [,1]       [,2]
[1,] 0.3459079 0.12934808
[2,] 0.1293481 0.04836815
```

So now I'm confused about the source of the error...

**Comment by carlbfrederick** [comment] 2015-07-08 14:56
There are two issues we need to address and both are unrelated to the condVar as you demonstrated (I was able to get conditional variance matrices too on multiple models).

I think that both are related to having multiple random coefficients per level though:

  1. For some sets of means/covariance matrices `mvtnorm::rmvnorm` produces `NaN`s  
  2. Also, we are only capturing `n.sims` of the numbers when `mvtnorm::rmvnorm` produces `2*n.sims` numbers in [lines 69-71](https://github.com/jknowles/merTools/blob/master/R/merPredict.R#L69-L71)

sub-issue 1 appears to be due to non-positive definite covariance matrices (see the stackoverflow exchange (with answer by Ben Bolker) [here](http://stackoverflow.com/questions/22463835/why-is-rmvnorm-function-returning-in-sqrtevvalues-nans-produced-what-i) ... the answer seems to be to either use `MASS::mvrnorm` or `mvtnorm::rmvnorm(method="svd")`

sub-issue 2 must have happened when we were speeding up the code.  The fix is to just put each random draw in its own layer and then make sure we are multiplying it by the correct variable later on when we are doing y hat .... this might entail creating a separate array for random intercepts (which are treated correctly as is) and each unique random slope (across all levels)

**Comment by jknowles** [comment] 2015-07-08 16:56
Nice diagnostic. So let's fix sub-issue 1 ASAP. Do you think there's a performance or other difference between `MASS` and `mvtnorm`. 

Sub-issue 2 is more tricky. Do you think throwing away 1/2 of the `2*n.sims` is problematic? If it is, then we'll need to do what you said and be careful about realigning the coefficients. I'm hoping we can keep the same mechanics we had before, but maybe you can look into it? 

Thanks for the diagnostic work!

**Comment by carlbfrederick** [comment] 2015-07-08 18:17
**RE: sub-issue 1 (let me know if you want me to fix it)** 

I am not sure about statistical issues, but from a speed perspective only I simulated a situation in which we are making 10,000 draws from a 40x40 matrix 4000 times.  This is mimicking a model with 40 random coefficients in a level with 4000 levels on the grouping factor and setting n.sims to 10,000

    #Generate a symmetric 40 by 40 covariance matrix
    a <- matrix(runif(1600, 0, 1), nrow=40)
    a <- a + t(a)
   
    #mvtnorm
    system.time(
      for (i in 1:4000) {
        b <- mvtnorm::rmvnorm(10000, mean=rep(0, nrow(a)), sigma=a,      method="svd")
      }
    )

    #MASS
    system.time(
      for (i in 1:4000) {
        b <- MASS::mvrnorm(10000, mu=rep(0, nrow(a)), Sigma=a, tol=1e0)
      }
    )

The difference is not very big, given the situation 
  *  `mvtnorm::rmvnorm` takes 221.32 total elapsed seconds (12.31 system time)
  * `MASS::mvrnorm` takes 200.16 total elapsed seconds (12.78 system time)

Statistically, I have no idea which is better ... the tolerance is very wide with MASS (the default is 1e06) and I have no idea how the singular value decomposition differs from the other methods.  Even though it is a tad slower, I think keeping `mvtnorm::rmvnrom` may be the way to go because we already import it and we only set a method not a tolerance level.

**RE: sub-issue 2**

It is problematic to treat the random multivariate draws the way that we do because (depending whether the data.frame fills row or column first) we are either taking the first 50 draws of for the intercept and first 50 draws of the random slope and filling them all into the random intercept slot or we are taking the entire 100 draws of the random intercept and ignoring any random deviation in the slopes.  

Unfortunately this will be somewhat involved, I think.

**Comment by jknowles** [comment] 2015-07-08 18:36
If you have time it'd be great if you could tackle issue 1. I agree with your analysis, better to stick with what we've been using and not muck around with tolerances, etc. 

Maybe let's tackle issue 2 together when I'm back. If you want to tackle it on your own before then (needing a break from something else) that's fine. Otherwise, we can hit the ground running early next week and I'm sure we'll be able to figure it out relatively quickly.

**Comment by carlbfrederick** [comment] 2015-07-08 18:42
Sounds great.  I will push a commit up once I have figured it out.  I agree
re: 2 ... taking some time to think it through before hacking up all the
code would be best.

Enjoy the conference!

**Closed** 2015-07-21 18:21 UTC
