### ISSUE TITLE
missing stripAttributes

### ISSUE THREAD

**Issue by Drinkysr** [jknowles/merTools#107] opened 2019-08-28 19:25 UTC
R version 3.6.1
R-studio version 1.2.1335
Windows 10 64-bit
===
library(merTools)
Loading required package: arm
Loading required package: MASS

Attaching package: ‘MASS’

The following object is masked from ‘package:dplyr’:

    select

Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:tidyr’:

    expand

Loading required package: lme4

arm (Version 1.10-1, built: 2018-4-12)

Working directory is C:/Users/CRL-User/Desktop/BNPCEA819

> cb <- read_sav('EXPORT_FILE_NT_PRO_BNP_CEA_2019.sav')
> names(cb) <- tolower(make.names(names(cb)))
> cb <- merTools::stripAttributes(cb)
Error: 'stripAttributes' is not an exported object from 'namespace:merTools'
> library(merTools)
> ?stripAttributes
> stripAttributes()
Error in stripAttributes() : could not find function "stripAttributes"
> require(merTools)
> stripAttributes()
Error in stripAttributes() : could not find function "stripAttributes"

**Comment by jknowles** [comment] 2019-09-05 21:35
I need the output from `sessionInfo()` at a minimum to diagnose this error. 

Even better would be submitting a [reprex](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219) so I can recreate the problem on my end.

**Comment by jknowles** [comment] 2020-01-13 19:37
Closing this because of a lack of a reprex. Please reopen if one is created.

**Closed by jknowles** 2020-01-13 19:37 UTC
